### ISSUE TITLE
Two extensions published

### ISSUE THREAD

**Issue by KamasamaK** [Togusa09/vscode-tmlanguage#12]
It appears that there are two extensions published from this same repository -- [Togusa09.tmlanguage](https://marketplace.visualstudio.com/items?itemName=Togusa09.tmlanguage) and the newer [Publisher2.tmlanguage](https://marketplace.visualstudio.com/items?itemName=Publisher2.tmlanguage). You should unpublish one of these to avoid confusion and fragmentation.

**Comment by Togusa09** [comment]
Thanks for letting me know, I hadn't realised that the publisher name was included in the package id when I regenerated the token. I've unpublished the Publisher2 version.
