### ISSUE TITLE
Converted file end up in subfolder with home structure

### ISSUE THREAD

**Issue by monoteba** [Togusa09/vscode-tmlanguage#2]
When I try to convert files, the results are put in a subfolder that has the same path as the project itself.

E.g.
`/Users/Morten/my-project/syntaxes/cs.YAML-tmLanguage`

will output the tmLanguage file to
`/Users/Morten/my-project/Users/Morten/my-project/syntaxes/cs.tmLanguage`

**Comment by Togusa09** [comment]
Thanks for reporting this.

Release v0.7.1 should fix this issue, can you please confirm this?

**Comment by monoteba** [comment]
Just tried it and seems to work perfectly!
