### ISSUE TITLE
Standalone conversion tool?

### ISSUE THREAD

**Issue by burner1024** [Togusa09/vscode-tmlanguage#22]
Any chance conversion gets released as a standalone tool? Running it manually all the time doesn't seem very efficient. Rather, including a command as a build step would be much more convenient.

**Comment by Togusa09** [comment]
I had a look at automating the conversion a while ago, and couldn't see any
practical options at the time.

This plugin is essentially just a wrapper around some other
parsing/serialisation libraries, so it may be possible to write an nodejs
script that runs outside of vscode to run the conversion.

**Comment by burner1024** [comment]
I see. If it's not in the plans, that's alright, I'll look into that myself. Just didn't want to create duplicate versions.
