### ISSUE TITLE
parse error on line 1:  ^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'' at: '1,1' source: ''

### ISSUE THREAD

**Issue by doivosevic** [Togusa09/vscode-tmlanguage#4]
For some reason after I install this extension in VSCODE 1.8 and open a json file and then open another file I get this error. I can repro it on 2 machines.

![image](https://cloud.githubusercontent.com/assets/6378638/21846098/bf9321bc-d7f5-11e6-91a8-e0278abcce25.png)

**Comment by Togusa09** [comment]
There's been some changes to the vscode libraries since the last release was made. I've updated the code to the latest libraries and will make a new release once I've tested the new package.

**Comment by Togusa09** [comment]
I've added a 0.8.0 release of the extension to resolve this issue. Could you please verify if it resolves your issue? https://github.com/Togusa09/vscode-tmlanguage/releases/tag/v0.8.0

Manual installation instructions: https://code.visualstudio.com/docs/extensions/install-extension#_install-from-a-vsix

**Comment by doivosevic** [comment]
I'm really sorry but I do not have a reproable environment anymore

**Comment by Togusa09** [comment]
Closing issue
